site_name: Developer Docs1
# Copyright
copyright: "Copyright &copy; Unacores AA Solutions Pvt Ltd."

extra_css:
  - css/custom.css

theme:
  name: "material"
  features:
    - navigation.footer
  logo: "images/ic_splash.png"
  palette:
    primary: "white"
    accent: "blue"
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.mark
extra:
  generator: true

# Page tree
nav:
  - Overview: index.md
  - Get Started: get_started.md
  - Registering with Ink AA: ink_aa_register.md
  - TSP Integration with Ink AA: ink_aa_integration.md
  - UI Integration with Ink AA: ink_ui_integration.md
  - Integrating with Ink FIU: ink_fiu_integration.md
  - How-To: how_to.md
  - Guidelines: guidelines.md
  # - Sample Test Data: fip_data_api.md
  # - FIP API Sandbox: fip_simulator.md
